spring.application.name=foodiesapi
spring.data.mongodb.uri=mongodb://localhost:27017/foodies
cloudinary.cloud-name=dyh2oxyg4
cloudinary.api-key=${CLOUDINARY_API_KEY}
cloudinary.api-secret=${CLOUDINARY_API_SECRET}

spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB
jwt.secret.key=qe2epcc2ahwtwdW8ewffewfwfewf2ewfw1ew5fewf1wf5wfw4fw5fw1fwe5fqw8fweewrwrwcwcdsvererve87

# Razorpay Configuration
razorpay.key.id=${RAZORPAY_KEY}
razorpay.key.secret=${RAZORPAY_SECRET}
